server:
  port: 8888
  contextPath: /
spring:
  application:
    name: apchy-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/onlyougit/apchy-config.git
eureka:
  instance:
    #是否显示主机得IP
    perfer-ip-address: true
  client:
    service-url:
      #注册中心得地址
      defaultZone: http://localhost:8761/eureka/